on:
  push:
    branches:
    - main

permissions:
  contents: write
    
jobs:
  build:
   
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Building website
      run : |
        npm -g install -g @angular/cli
        npm install
        ng build --optimization --output-path docs --base-href /tony-nguyen1.github.io/
    - name: Saving the output
      uses: actions/upload-artifact@v1
      with:
        name: my_website
        path: docs/
    - name: Checking
      run : ls -R docs/
       
        
  deploy:
  
    runs-on: ubuntu-latest
    
    needs: build
   
    steps:
        - name: Download build
          uses: actions/download-artifact@v1
          with:
            name: my_website

        - name: Initialize git repository
          env: 
            SSH_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          run: |
            git init
            git config --global user.name "Mr.Beep-Boop"
            git config --global user.email "nguyentoony@gmail.com"
            eval "$(ssh-agent -s)"
            echo $SSH_KEY
            ssh-add -l
            echo $SSH_KEY >> ssh_key.txt
            ssh-add ./ssh_key.txt
            ssh-add -l

        - name: Checking
          run : |
            pwd
            git status
            ls -aR
            cd ../
            pwd
            ls
        - name: Adding everything
          run : |
            git status
            git add .
            git status
        - name: Pushing
          run : |
            git commit -m "deploy"
            git branch -M main
            git remote add origin git@github.com:tony-nguyen1/tony-nguyen.github.io.git
            git push -u origin main --force
            
        # - name: Deploy to GitHub Pages
        #   uses: JamesIves/github-pages-deploy-action@releases/v4
        #   with:
        #     token: ${{ secrets.GITHUB_TOKEN }}
        #     branch: main
        #     folder: my_website
        #     repository-name: tony-nguyen1/tony-nguyen1.github.io
        #     git-config-name: beep-boop
        #     commit-message: "automatic deployment"
        #     single-commit: true 
        # - name: Pushes to another repository
        #   uses: cpina/github-action-push-to-another-repository@main
        #   env:
        #   # SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        #     API_TOKEN_GITHUB: ${{ secrets.SSH_DEPLOY_KEY }}
        #   with:
        #     source-directory: 'my_website'
        #     destination-github-username: 'tony-nguyen1'
        #     destination-repository-name: 'tony-nguyen1.github.io'

