on:
  push:
    branches:
    - main

permissions:
  contents: write
    
jobs:
  build:
   
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Building website
      run : |
        npm -g install -g @angular/cli
        npm install
        ng build --optimization --output-path docs --base-href /tony-nguyen1.github.io/
    - name: Saving the output
      uses: actions/upload-artifact@v1
      with:
        name: my_website
        path: docs/
    - name: Checking
      run : ls -R docs/
       
        
  deploy:
  
    runs-on: ubuntu-latest
    
    needs: build
   
    steps:
        - name: Download build
          uses: actions/download-artifact@v1
          with:
            name: my_website

        - name: Initialize git repository
          run: |
            git init
        
        - name: Checking
          run : |
            pwd
            ls -R
            cd ../
            ls
            
        - name: Deploy to GitHub Pages
          uses: JamesIves/github-pages-deploy-action@releases/v4
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            branch: main
            folder: my_website
            repository-name: tony-nguyen1/tony-nguyen1.github.io
            git-config-name: beep-boop
            commit-message: "automatic deployment"
            single-commit: true 
